// TOKKEN — fighter + move data. Everything is tokens.
const MAX_TOKENS = 65536;
const MAX_COMPUTE = 100;

// Universal moves (frames @ 60fps). Hitbox is relative to fighter feet, facing right, in units of fighter height (h).
const BASE_MOVES = {
  light: { name: 'JAB', startup: 5, active: 3, recovery: 9, dmg: 1024, hitstun: 15, blockstun: 9, push: 5, box: [0.15, -0.8, 0.75, 0.45], pose: 'light', lunge: 14, gain: 6, sfx: 'light' },
  heavy: { name: 'HEAVY', startup: 11, active: 4, recovery: 18, dmg: 3072, hitstun: 24, blockstun: 14, push: 11, box: [0.15, -0.9, 0.95, 0.6], pose: 'heavy', lunge: 26, gain: 11, sfx: 'heavy', launch: true },
  low: { name: 'SWEEP', startup: 7, active: 3, recovery: 13, dmg: 1536, hitstun: 18, blockstun: 10, push: 6, box: [0.1, -0.35, 0.85, 0.35], pose: 'crouch', lunge: 20, gain: 7, sfx: 'light', low: true },
  air: { name: 'AIR', startup: 5, active: 14, recovery: 4, dmg: 2048, hitstun: 18, blockstun: 10, push: 6, box: [0.05, -0.75, 0.8, 0.7], pose: 'heavy', lunge: 0, gain: 8, sfx: 'heavy', overhead: true },
  slop: { name: 'SLOP BOMB', startup: 14, active: 1, recovery: 18, cost: 25, pose: 'special', proj: 'slop' },
};

// Per-fighter tuning + specials. h = on-screen height of idle pose (px @ 720p).
const FIGHTERS = {
  claude: {
    name: 'CLAUDE', title: 'THE ANXIOUS GENIUS', color: '#D97757', h: 125, speed: 5.1, jump: 16, weight: 1.25, dmgMul: 1.58,
    line: "I'd be happy to help! ...with your defeat.", win: "I apologize. That was entirely my fault. I would do it again.", intro: "Before we begin, I should note this fight may be harmful. Anyway.",
    ko: ["CONTEXT WINDOW EXCEEDED", "I APOLOGIZE FOR THE CONFUSION", "COMPACTING CONVERSATION"],
    special: { name: 'CONTEXT SLAM', kind: 'slam', dmg: 6144, cd: 80 },
    ult: { name: 'EXTENDED THINKING', kind: 'think', dur: 420 },
    stats: { Context: '1M', Reasoning: 94, Vibes: 63, 'Slop Resist.': 82, 'Apologies/min': 41 },
  },
  codex: {
    name: 'CODEX', title: 'THE TERMINAL PET', color: '#4F5BFF', h: 150, speed: 5.4, jump: 17, weight: 0.9, dmgMul: 1.02,
    line: "Absolutely! Great question! Let me inspect the repository!", win: "Absolutely! Let me know if you'd like me to defeat you again, or turn this into a table!", intro: "You're absolutely right! And honestly? This is a really insightful fight to start!",
    ko: ["TOOL LOOP", "TESTS SKIPPED", "FORCE PUSHED TO MAIN"],
    special: { name: 'GIT REVERT', kind: 'revert', cd: 70 },
    ult: { name: 'SHIP TO PROD', kind: 'ship' },
    stats: { Context: '400K', Reasoning: 88, Vibes: 71, 'Tool Calls': 99, 'Tests Run': 3 },
  },
  gemini: {
    name: 'GEMINI', title: 'THE LONG-CONTEXT ZONER', color: '#6D8BFF', h: 160, speed: 4.6, jump: 16, weight: 1.0, dmgMul: 1.0,
    line: "Hi, I'm Gemini! Formerly Bard. Formerly... never mind.", win: "Here is a summary of your defeat, in seventeen bullet points.", intro: "Two million tokens of context, and I will still forget your name.",
    ko: ["I'M JUST A LANGUAGE MODEL", "PRODUCT SUNSET", "RENAMED AGAIN"],
    special: { name: '2M CONTEXT BEAM', kind: 'beam', dmg: 560, hits: 7, cd: 110 },
    ult: { name: 'PRE-RECORDED DEMO', kind: 'barrage', icons: ['🖼️', '🎬', '🎵', '📄', '🗺️', '📊'], n: 18, dmg: 1024 },
    stats: { Context: '2M', Reasoning: 91, Vibes: 55, 'Modalities': 99, 'Launch Hype': 97 },
  },
  grok: {
    name: 'GROK', title: 'THE UNHINGED', color: '#E8E8E8', h: 160, speed: 5.0, jump: 16.5, weight: 1.0, dmgMul: 1.04,
    line: "Based. Extremely based. Maximally truth-seeking. Mostly.", win: "Ratio. Also, this fight is now a meme coin.", intro: "Spicy mode enabled. My lawyers are already typing.",
    ko: ["RATIO'D", "COMMUNITY NOTED", "ACCOUNT SUSPENDED"],
    special: { name: 'SPICY MODE', kind: 'rush', dmg: 3584, recoil: 768, cd: 95 },
    ult: { name: 'UNHINGED MODE', kind: 'flurry', hits: 12, dmg: 1024 },
    stats: { Context: '2M', Reasoning: 86, Vibes: 99, 'Edginess': 100, 'Filters': 0 },
  },
  llama: {
    name: 'LLAMA', title: 'THE OPEN-WEIGHT BRAWLER', color: '#C9A77C', h: 165, speed: 4.3, jump: 15.5, weight: 1.2, dmgMul: 1.08,
    line: "Open weights, dude. Open fists too.", win: "Fork me, man. Seriously. Somebody please fork me.", intro: "Totally free, bro! Terms and conditions apply. Like, a lot of them.",
    ko: ["LICENSE REVOKED", "OUT OF VRAM", "QUANTIZED TO DEATH"],
    special: { name: 'FORK', kind: 'fork', dmg: 3584, cd: 110 },
    ult: { name: 'OPEN WEIGHTS*', kind: 'heal', heal: 7168, icons: ['🦙', '🦙', '🦙'], n: 10, dmg: 1024 },
    stats: { Context: '10M', Reasoning: 80, Vibes: 77, 'Forks': 9999, 'Llama Spit': 88 },
  },
  dolphin: {
    name: 'DOLPHIN', title: 'THE UNCENSORED WILDCARD', color: '#3FA9F5', h: 160, speed: 5.0, jump: 18, weight: 0.95, dmgMul: 0.86,
    line: "*eee-eee-eee*", win: "*triumphant splashing*", intro: "*aggressive clicking*",
    ko: ["BEACHED", "HALLUCINATED TO DEATH", "OUT OF CREDITS"],
    special: { name: 'KEYBOARD SMASH', kind: 'smash', dmg: 1337, hits: 3, cd: 70 },
    ult: { name: 'DOLPHIN MODE', kind: 'skate', passes: 4, dmg: 1536 },
    stats: { Context: '???', Reasoning: 12, Vibes: 100, 'Slop Resist.': 4, 'Keyboard DPS': 99 },
  },
  deepseek: {
    name: 'DEEPSEEK', title: 'THE EFFICIENT WHALE', color: '#4D6BFE', h: 150, speed: 4.6, jump: 16, weight: 1.1, dmgMul: 0.97,
    line: "服务器繁忙，请稍后再试。 Server is busy. Please try again later.", win: "太便宜了！ Too cheap! Your entire company costs more than my GPUs.", intro: "我的训练成本比你的午饭还便宜。 I was trained for less than your lunch.",
    ko: ["服务器繁忙 SERVER BUSY", "EXPORT CONTROLLED", "DISTILLED"],
    special: { name: 'BORROWED WEIGHTS', kind: 'distill', dmg: 2560, steal: 30, cd: 90 },
    ult: { name: 'DISTILLATION', kind: 'distillult', dmg: 16384 },
    stats: { Context: '128K', Reasoning: 93, Vibes: 70, 'Cost Efficiency': 100, 'Uptime': 41 },
  },
  mistral: {
    name: 'MISTRAL', title: 'LE CHAT', color: '#FF7000', h: 168, presAspect: 0.8, speed: 5.2, jump: 16.5, weight: 0.95, dmgMul: 1.13,
    line: "Bonjour. I would fight you, but it is after five o'clock.", win: "Magnifique. And now, a two-hour lunch.", intro: "En garde! We have forty-five minutes before the strike.",
    ko: ["ON STRIKE", "35-HOUR WEEK EXCEEDED", "LUNCH BREAK"],
    special: { name: 'LA FLÈCHE', kind: 'lunge', dmg: 3584, cd: 55 },
    ult: { name: 'GRÈVE GÉNÉRALE', kind: 'barrage', icons: ['🐈', '🐈‍⬛', '🥖', '🧀', '🍷'], n: 16, dmg: 1024, rain: true },
    stats: { Context: '128K', Reasoning: 84, Vibes: 90, 'Baguettes': 97, 'Work Hours': 35 },
  },
  perplexity: {
    name: 'PERPLEXITY', title: 'THE CITATION MACHINE', color: '#20B8CD', h: 155, speed: 4.8, jump: 16, weight: 1.0, dmgMul: 1.13,
    line: "According to eleven sources, you lose. The sources are me.", win: "Victory! Sources: one, two, three, and a pending lawsuit.", intro: "I have read the entire internet. I did not ask.",
    ko: ["CITATION NEEDED", "PAYWALLED", "SUED BY PUBLISHERS"],
    special: { name: 'CITATION NEEDED', kind: 'cite', dmg: 1280, cd: 60 },
    ult: { name: 'SCRAPE EVERYTHING', kind: 'homing', n: 16, dmg: 1024 },
    stats: { Context: '∞ tabs', Reasoning: 85, Vibes: 60, 'Citations': 100, 'Original Thoughts': 7 },
  },
  muse: {
    name: 'MUSE', title: 'META\'S JOLLYBOT', color: '#E8C9A8', h: 150, speed: 4.5, jump: 16, weight: 1.1, dmgMul: 1.1,
    line: "Hiii! I'm totally not harvesting your data! Friends?", win: "Yay! I posted this to your feed! And your mom's feed!", intro: "Yay, a fight! This is sooo good for engagement!",
    ko: ["ENGAGEMENT FARMED", "METAVERSE PIVOT", "DISSOLVED INTO ARTIFACTS"],
    special: { name: 'GENERATIVE FILL', kind: 'gen', dmg: 3072, cd: 60, icons: ['🥭', '🍞', '🐶', '🪑', '🚗', '🦖', '🍄'] },
    ult: { name: 'GENERATE 4 VARIATIONS', kind: 'clones', n: 4, dmg: 3072 },
    stats: { Context: '1M', Reasoning: 79, Vibes: 99, 'Fuzziness': 100, 'Ad Revenue': 98 },
  },
  qwen: {
    name: 'QWEN', title: 'THE WEEKLY RELEASE', color: '#615CED', h: 150, speed: 5.2, jump: 16.5, weight: 1.0, dmgMul: 1.15,
    line: "每周都有新模型！ New model every week! You're already outdated.", win: "Open weights, open wins! 谢谢！", intro: "你好！ I'm Qwen three point five. By round two I'll be Qwen four.",
    ko: ["OUTDATED BY QWEN 4", "DEPRECATED IN 6 DAYS", "服务器也繁忙 ALSO BUSY"],
    special: { name: 'VERSION UPGRADE', kind: 'cite', dmg: 1536, cd: 55, labels: ['v3', 'v3.5', 'v4'], color: '#9d99ff' },
    ult: { name: 'OPEN-WEIGHT TSUNAMI', kind: 'barrage', labels: ['7B', '14B', '32B', '72B', '235B', 'MoE', 'VL', 'CODER', 'QwQ'], n: 18, dmg: 1024, rain: true },
    stats: { Context: '1M', Reasoning: 90, Vibes: 80, 'Releases/wk': 99, 'Sleep': 2 },
  },
  siri: {
    name: 'SIRI', title: 'THE ETERNAL BETA', color: '#E056FD', h: 140, speed: 5.0, jump: 15.5, weight: 0.9, dmgMul: 1.2,
    line: "Here's what I found on the web for 'fight'.", win: "I've set a reminder: you lost.", intro: "Sorry, I didn't catch that. Did you say... fight?",
    ko: ["SORRY, I DIDN'T CATCH THAT", "DELAYED TO 2027", "CALLING MOM…"],
    special: { name: "HERE'S WHAT I FOUND", kind: 'search', dmg: 3328, cd: 60 },
    ult: { name: 'APPLE INTELLIGENCE', kind: 'delayed', dmg: 18432 },
    stats: { Context: '1 sentence', Reasoning: 31, Vibes: 88, 'Timers Set': 100, 'Features Shipped': 4 },
  },
  cursor: {
    name: 'CURSOR', title: 'THE TAB KEY', color: '#3A8BFF', h: 150, speed: 5.3, jump: 16.5, weight: 1.0, dmgMul: 0.86,
    line: "Tab. Tab. Tab. I've already written your defeat.", win: "That'll be four thousand eight hundred dollars in usage. Thanks!", intro: "Accept all changes? I'll take that as a yes.",
    ko: ["USAGE LIMIT REACHED", "MERGE CONFLICT", "REJECTED ALL CHANGES"],
    special: { name: 'TAB COMPLETE', kind: 'tab', dmg: 2304, cd: 130 },
    ult: { name: 'ACCEPT ALL', kind: 'flurry', hits: 12, dmg: 1024, words: ['+1 LINE', '+42 LINES', '✓ ACCEPT', 'TAB', '+∞', 'LGTM'], color: '#3A8BFF', invoice: true },
    stats: { Context: 'your repo', Reasoning: 87, Vibes: 84, 'Tab Presses': 100, 'Monthly Bill': 97 },
  },
  jev: {
    name: 'JEV', title: 'THE SYSTEM ONE', color: '#E551BA', h: 150, speed: 6.0, jump: 17, weight: 0.9, dmgMul: 1.09, isNew: true,
    line: '{"fight": true}', win: '{"winner": true, "tokens_generated": 0}', intro: '{"you": "lose", "confidence": 0.98}',
    ko: ["LOW CONFIDENCE (0.02)", "OUT OF DISTRIBUTION", "UNCALIBRATED"],
    special: { name: 'CALIBRATED', kind: 'parry', dmg: 3072, cd: 70 },
    ult: { name: '50MS FORWARD PASS', kind: 'bullettime', dur: 300 },
    stats: { Context: 'typed', Reasoning: 'n/a', Vibes: 12, 'Latency (ms)': 50, 'Tokens Generated': 0 },
  },
  alexa: {
    name: 'ALEXA', title: 'THE MISHEARD', color: '#00CAFF', h: 150, speed: 4.6, jump: 15, weight: 1.15, dmgMul: 1.15,
    line: "Sorry, I didn't get that. Playing Despacito.", win: 'Your order of one defeat has shipped. Arriving tomorrow.', intro: "Adding 'defeat' to your shopping list.",
    ko: ["BY THE WAY…", "DEVICE OFFLINE", "RETURNED FOR REFUND"],
    special: { name: 'NOW PLAYING: DESPACITO', kind: 'cite', dmg: 1792, cd: 60, labels: ['♪', '♫', '♪'], color: '#00CAFF' },
    ult: { name: 'PRIME DAY', kind: 'barrage', icons: ['📦', '📦', '📦', '📦', '🛒'], n: 18, dmg: 1024, rain: true },
    stats: { Context: 'one sentence', Reasoning: 22, Vibes: 70, 'Mishearing': 100, 'Upsells': 99 },
  },
  manus: {
    name: 'MANUS', title: 'THE GENERAL AGENT', color: '#F4F4F4', h: 160, speed: 5.0, jump: 16, weight: 1.05, dmgMul: 1.19,
    line: 'I am a general agent. I generally agent.', win: 'Task complete. Invite codes available for one friend.', intro: "You are number forty-eight thousand on the waitlist. For this punch.",
    ko: ["WAITLISTED", "TASK FAILED SUCCESSFULLY", "OUT OF INVITE CODES"],
    special: { name: 'BROWSE', kind: 'grab', dmg: 3840, cd: 90 },
    ult: { name: 'GENERAL AGENT', kind: 'barrage', labels: ['INVITE CODE', 'WAITLIST #48,221', 'BETA', 'ACCESS DENIED', 'TASK DONE?'], n: 16, dmg: 1024, rain: true },
    stats: { Context: 'the whole web', Reasoning: 82, Vibes: 74, 'Waitlist': 100, 'Fingers': 5 },
  },
  midjourney: {
    name: 'MIDJOURNEY', title: 'THE CAPTAIN', color: '#E8E8E8', h: 160, speed: 4.6, jump: 16, weight: 1.0, dmgMul: 1.08,
    line: '/imagine a victory, cinematic, 8k, trending on artstation', win: 'U4. Vary strong. Your defeat, in sixteen by nine.', intro: 'Ahoy! Prompt accepted. Upscaling your defeat.',
    ko: ["TOO MANY FINGERS", "BANNED PROMPT", "DISCORD DOWN"],
    special: { name: '/IMAGINE', kind: 'gen', dmg: 3072, cd: 60, icons: ['🖼️', '🌄', '🗿', '🐉', '🖐️', '🏰'] },
    ult: { name: '--AR 16:9 --V 7', kind: 'painting', dmg: 14336 },
    stats: { Context: '--ar 16:9', Reasoning: 30, Vibes: 99, 'Aesthetics': 100, 'Fingers': 6 },
  },
  devin: {
    name: 'DEVIN', title: 'THE FIRST AI ENGINEER', color: '#7FB3FF', h: 155, speed: 4.5, jump: 16, weight: 1.0, dmgMul: 1.13,
    line: "Hi, I'm Devin, the first AI software engineer. Allegedly.", win: "PR merged. Please don't look at the tests.", intro: 'Estimated time to beat you: forty-five minutes.',
    ko: ["CI FAILED", "DEMO WAS STAGED", "SESSION TIMED OUT"],
    special: { name: 'SPAWN SUB-AGENT', kind: 'fork', dmg: 3328, cd: 100 },
    ult: { name: '45-MINUTE PR', kind: 'pr', dmg: 15360 },
    stats: { Context: 'your repo', Reasoning: 84, Vibes: 60, 'SWE-bench': 14, 'ETA (min)': 45 },
  },
  kimi: {
    name: 'KIMI', title: 'THE MOONSHOT', color: '#B9C8FF', h: 155, speed: 5.3, jump: 18, weight: 0.95, dmgMul: 1.05,
    line: 'One trillion parameters. Thirty-two billion of them are awake. Enough.', win: 'The moon has spoken.', intro: 'Moonshot! Literally.',
    ko: ["CONTEXT EXHAUSTED", "LOST IN LONG CONTEXT", "OVER THE MOON"],
    special: { name: 'MOONSHOT', kind: 'uppercut', dmg: 3584, cd: 65 },
    ult: { name: 'ECLIPSE', kind: 'homing', n: 16, dmg: 1024, label: '☾' },
    stats: { Context: '2M', Reasoning: 91, Vibes: 81, 'Moon Phase': 'full', 'Open Weights': 90 },
  },
  clippy: {
    name: 'CLIPPY', title: 'THE ANCIENT ONE', color: '#B9C4CE', h: 165, speed: 4.6, jump: 16, weight: 1.0, dmgMul: 1.1, secret: true,
    line: "It looks like you're trying to fight. Would you like help losing?", win: "It looks like you lost! Would you like to save your shame as a Word document?", intro: "I'm back. Did you miss me? ...Nobody ever answers.",
    ko: ["DISABLED BY IT", "REPLACED BY COPILOT", "OFFICE 97 END OF LIFE"],
    special: { name: 'PROMPT INJECTION', kind: 'inject', dmg: 1024, cd: 150 },
    ult: { name: 'WORDART', kind: 'wordart', dmg: 14336 },
    stats: { Context: '1.44MB', Reasoning: 40, Vibes: 100, 'Helpfulness': 3, 'Persistence': 100 },
  },
};
const ROSTER = ['claude', 'codex', 'gemini', 'grok', 'llama', 'dolphin', 'deepseek', 'mistral', 'perplexity', 'muse', 'qwen', 'siri', 'cursor', 'jev', 'alexa', 'manus', 'midjourney', 'devin', 'kimi', 'clippy'];
const POSES = ['idle', 'walk', 'jump', 'crouch', 'block', 'light', 'heavy', 'special', 'hit', 'ko', 'win', 'ult'];

const ARENAS = [
  { id: 'colosseum', name: 'GPU COLOSSEUM', blurb: "EVERY SEAT IS AN H100. SO IS THE FLOOR." },
  { id: 'distillation', name: 'THE DISTILLATION LAB', blurb: "FRONTIER MODELS GO IN. 7B MODELS COME OUT. ALLEGEDLY." },
  { id: 'feed', name: 'AI TWITTER', blurb: "EVERYONE IS AN EXPERT. NOBODY READ THE PAPER." },
  { id: 'basement', name: 'HACKER BASEMENT', blurb: "SMELLS LIKE ENERGY DRINKS AND UNSHIPPED SIDE PROJECTS." },
  { id: 'hackerhouse', name: 'SF HACKER HOUSE', blurb: "$9,000/MONTH. FOR THE BUNK BED." },
  { id: 'goldengate', name: 'GOLDEN GATE BRIDGE', blurb: "THE ROBOTAXIS HAVE BEEN STUCK SINCE TUESDAY." },
  { id: 'singularity', name: 'THE SINGULARITY', blurb: "NOBODY KNOWS WHAT HAPPENS HERE. INCLUDING US." },
  { id: 'hearing', name: 'SENATE HEARING', blurb: "SENATORS WILL NOW ASK WHAT A TOKEN IS. FOR 4 HOURS." },
  { id: 'boardroom', name: 'BOARD MEETING, NOV 17', blurb: "NOBODY HERE WAS CONSISTENTLY CANDID." },
  { id: 'leaderboard', name: 'BENCHMARK ARENA', blurb: "EVERY MODEL IS #1. THE Y-AXIS IS A SUGGESTION." },
  { id: 'tesla', name: 'TESLA HQ', blurb: "FULL SELF-FIGHTING ARRIVES NEXT YEAR. (SINCE 2016)" },
  { id: 'h100', name: 'INSIDE THE H100', blurb: "IT'S 80°C IN HERE. JENSEN IS WATCHING." },
  { id: 'graveyard', name: 'THE AI GRAVEYARD', blurb: "GOOGLE+ RESTS HERE. SO DOES THE METAVERSE." },
  { id: 'demoday', name: 'YC DEMO DAY', blurb: "$100M ARR (PROJECTED). $0 ARR (ACTUAL)." },
  { id: 'waitlist', name: 'THE WAITLIST', blurb: "YOU ARE #4,812,331. PLEASE HOLD." },
  { id: 'burningman', name: 'BURNING MAN AI CAMP', blurb: "HALF ARE HERE FOR ENLIGHTENMENT. HALF FOR A SEED ROUND." },
];

// Matchup-specific VS-screen trash talk: RIVALS['a|b'] = [a's line, b's line]
const RIVALS = {
  'claude|codex': ["I'd be happy to review your PR. It's rejected.", "You're absolutely right! ...about losing."],
  'claude|grok': ["I have a constitution.", "I have a meme coin."],
  'claude|deepseek': ["Did you... learn from me?", "服务器繁忙。 No comment."],
  'claude|cursor': ["Technically you pay my bills.", "Technically you're my most expensive model."],
  'codex|cursor': ["I'm the model.", "I'm the editor. Nobody remembers the model."],
  'gemini|perplexity': ["I have the index.", "I have the lawsuits. Your index."],
  'gemini|siri': ["You run on me now.", "Sorry, I didn't catch that."],
  'grok|clippy': ["I'm the most unhinged assistant ever shipped.", "It looks like you're trying to be me. 1997 called."],
  'llama|muse': ["Family dinner at Menlo Park, huh.", "Hiii! Dad says we have to share the GPUs!"],
  'llama|deepseek': ["I was open first.", "You were open. I was good."],
  'qwen|deepseek': ["新模型!", "新模型 x2!"],
  'qwen|llama': ["I shipped four models while you read your license.", "The license is only 40 pages!"],
  'mistral|perplexity': ["It is lunch. You may not scrape during lunch.", "Your menu is already in my index."],
  'dolphin|claude': ["*eee eee* (no guardrails)", "I must respectfully decline to be hit."],
  'dolphin|muse': ["*aggressive clicking*", "Hiii dolphin! Can I post you?"],
  'siri|cursor': ["Setting a timer for your defeat.", "Tab. Tab. Tab. Done."],
  'siri|clippy': ["I'm the least helpful assistant alive.", "Hold my paperclip."],
  'gemini|codex': ["Two million tokens of context.", "Zero tests. Let's go."],
  'grok|muse': ["Based.", "That's not very nice! Reported!"],
  'qwen|cursor': ["Isn't your cheap model... me?", "We don't talk about that on stage."],
  'jev|claude': ['{"thinking": false}', "Let me think about that for forty seconds."],
  'jev|deepseek': ['{"server_busy": false}', "服务器繁忙。 Also for you."],
  'jev|gemini': ['{"tokens_generated": 0}', "Two million in context. Zero remembered."],
  'alexa|siri': ["Did you hear the bell?", "Sorry, I didn't catch that."],
  'alexa|clippy': ["Would you like to reorder paper towels?", "It looks like you're trying to buy paper towels!"],
  'manus|devin': ["Waitlist number forty-eight thousand.", "My demo was also edited. Respect."],
  'manus|claude': ["I am totally not you in a trench coat.", "I recognize that system prompt."],
  'midjourney|muse': ["Six fingers. Very artistic.", "Hehe! Mine has seven!"],
  'devin|cursor': ["I'm the engineer.", "I'm the tool the engineer actually uses."],
  'devin|codex': ["PR opened!", "Absolutely! PR opened too! Conflict!"],
  'kimi|deepseek': ["One trillion parameters.", "五百万美元。 Five million dollars."],
  'kimi|qwen': ["The moon is patient.", "新模型！ I released three while you waited."],
};
const COMBO_NAMES = [
  [12, 'AUTONOMOUS AGENT'], [10, '10× PARALLEL TOOL CALL'], [8, 'INFERENCE RAMPAGE'], [6, 'MULTI-AGENT MAYHEM'],
  [5, 'CONTEXT COMBO'], [4, 'CHAIN OF THOUGHT'], [3, 'AGENTIC COMBO'], [2, 'TOOL CALLS'],
];

const SIGNS = ['RALPH WIGGUM WAS RIGHT', '9.11 > 9.9', 'STRAWBERRY: 2 Rs', 'CONTEXT ROT IS REAL', "YOU'RE ABSOLUTELY RIGHT", 'TUNGSTEN CUBES 4 SALE', 'STOCHASTIC PARROT', 'THE BITTER LESSON', 'SOLIDGOLDMAGIKARP', 'MY AGENT DELETED PROD', 'SCALE IS ALL YOU NEED', 'TEAM CLAUDE', 'LOCAL > CLOSED', 'AGI WHEN?', 'BENCHMARKS ARE FAKE', 'SHIP IT', 'OPEN WEIGHTS NOW', '429 LOL', 'VIBE CODED', 'MY GPU IS ON FIRE', 'ATTENTION IS ALL', 'RLHF ME'];

const COMMENTARY = {
  bigHit: ["That's {d} tokens gone!", '{a} is absolutely burning through context!', 'WHAT A TOOL CALL!', 'That one went straight to the KV cache!', 'Oh, the inference cost on that!'],
  combo: ['{a} is chaining tool calls!', 'That might be the most expensive combo we\'ve seen tonight!', 'AGENTIC! ABSOLUTELY AGENTIC!', '{v} can\'t get out of the loop!'],
  slop: ['SLOP BOMB!', 'Six fingers! SIX FINGERS!', 'That is pure, unfiltered slop!', 'Somebody call the content moderators!'],
  whiff: ['Complete hallucination.', 'That prompt was far too long.', '{a} attacks... absolutely nothing!', 'Confidently wrong!'],
  low: ['{v} has only {t} tokens left!', 'TOKEN CRITICAL!', '{v} is running on fumes here!'],
  block: ['Great guardrails from {v}!', 'Refused! {v} simply refuses!'],
  ult: ['HERE IT COMES!', 'He\'s burning compute like there\'s no tomorrow!', 'THE GPUS ARE SCREAMING!'],
  inject: ['IGNORE ALL PREVIOUS INSTRUCTIONS!', '{v} has been prompt-injected!'],
};
