import { chromium } from 'playwright';
const b = await chromium.launch(); const p = await (await b.newContext({ viewport: { width: 1280, height: 720 } })).newPage();
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('https://tokken-6t6.pages.dev/'); await p.waitForFunction(() => window.TOKKEN && TOKKEN.scene === 'title');
const k = async key => { await p.keyboard.press(key); await p.evaluate(() => TOKKEN.tick(4)); };
const sc = () => p.evaluate(() => TOKKEN.scene + (update.paused ? '(paused)' : '') + ' done=' + sel.done.join(','));
const log = [];
await k('Enter'); await k('Enter'); log.push('vs cpu → ' + await sc());
await k('KeyF'); log.push('lock P1 → ' + await sc());
await k('Escape'); log.push('ESC while picking CPU → ' + await sc());
await k('Escape'); log.push('ESC again → ' + await sc());
await k('Enter'); await k('KeyF'); await k('KeyF'); log.push('both locked → ' + await sc());
await k('Escape'); log.push('ESC on stage → ' + await sc());
await k('KeyF'); await k('KeyF'); await k('Enter'); await p.evaluate(() => TOKKEN.tick(30)); log.push('to VS → ' + await sc());
await k('Escape'); log.push('ESC on VS → ' + await sc());
await k('Enter'); await p.evaluate(() => TOKKEN.tick(400)); log.push('fight → ' + await sc());
await k('Escape'); log.push('ESC in fight → ' + await sc());
await k('Escape'); log.push('ESC in pause → ' + await sc());
await k('Escape'); await k('ArrowDown'); await k('ArrowDown'); await k('Enter'); log.push('pause → QUIT TO TITLE → ' + await sc());
console.log(log.join('\n'), '\nerrors:', errs.length);
await b.close();
