# TOKKEN commentary booth: BRAD GRADIENT (P, hype play-by-play) + DR. NIGEL OVERFIT (N, dry analyst).
# Each entry: list of (speaker, line) played in sequence.
B = {
 # --- match / round flow
 'open': [
   [('P', "Good evening and welcome to TOKKEN! I'm Brad Gradient!"), ('N', "And I'm Doctor Nigel Overfit. I'm here because my startup ran out of runway.")],
   [('P', "Welcome, fight fans! Tonight's event is brought to you by an unsustainable burn rate!"), ('N', "And a cap table that looks like modern art.")],
   [('P', "The weights are loaded! The GPUs are warm!"), ('N', "The valuations remain completely detached from reality.")],
   [('P', "Two agents enter! One context window leaves!"), ('N', "Legally, both of them are still in beta.")],
   [('P', "What a night! Sold out crowd! Every seat filled!"), ('N', "Mostly with VCs looking for their next pivot.")],
 ],
 'round2': [[('P', "Round two! He needs a comeback!"), ('N', "Or a better system prompt.")], [('P', "Round two, and the tension is unbearable!"), ('N', "So is the latency.")]],
 'final': [[('P', "FINAL ROUND! Everything on the line!"), ('N', "Including Series B.")], [('P', "It all comes down to this!"), ('N', "Like most AI demos. One take, pray it works.")]],
 'matchpoint': [[('P', "One more round and it's over!"), ('N', "Much like the hype cycle.")]],
 'firsthit': [[('P', "First blood! Well, first tokens!")], [('P', "And we're off! First contact!"), ('N', "Unlike most AI products, it actually shipped.")], [('P', "Opening strike lands!")]],
 'timelow': [[('P', "Ten seconds left on the clock!"), ('N', "Somebody please ship something.")], [('P', "Time is running out!"), ('N', "Just like the free trial.")]],
 'perfect': [[('P', "A PERFECT ROUND! Not a single token lost!"), ('N', "First time I've seen zero hallucinations. Suspicious, honestly.")]],
 'comeback': [[('P', "Wait a minute! Look at this comeback!"), ('N', "He found a second funding round.")], [('P', "From the free tier to the top! What a turnaround!")], [('P', "Don't count him out! He's rebooting!"), ('N', "Turning it off and on again. The oldest fix in the book.")]],
 'neutral': [
   [('N', "Nobody's committing. Classic enterprise procurement.")],
   [('N', "Lot of walking around. Reminds me of every standup meeting I've ever attended.")],
   [('P', "They're circling each other!"), ('N', "Like two chatbots trying to end a conversation politely.")],
   [('N', "This is what we call the evaluation phase. Nobody knows what's happening, but everyone has a dashboard.")],
   [('P', "Cautious play from both agents!"), ('N', "They're waiting for the legal team to approve the next punch.")],
   [('N', "Fun fact, Brad. This fight has already used more electricity than Belgium.")],
   [('N', "Still nothing. Honestly, I could write a whitepaper in this time.")],
 ],
 'turtle': [[('P', "He's blocking everything!"), ('N', "Maximum guardrails. Zero helpfulness. Very safe product.")], [('N', "That's a lot of refusals. I asked for a punch, not a policy document.")]],
 'jumpspam': [[('P', "He's jumping around like crazy!"), ('N', "Hyperparameter search. No strategy, just vibes.")]],
 'whiff': [
   [('P', "He swings... AT NOTHING!"), ('N', "Confidently wrong. We love to see it.")],
   [('N', "That's a hallucination, Brad. He attacked a benchmark that doesn't exist.")],
   [('P', "A complete miss!"), ('N', "But he'll write a blog post saying it landed.")],
   [('N', "He whiffed, and I guarantee the press release says record performance.")],
 ],
 'block': [[('P', "Blocked!"), ('N', "I'm sorry, I can't help with that.")], [('P', "Great defense!"), ('N', "Great guardrails. Terrible user experience.")], [('P', "Denied!")]],
 'bighit': [
   [('P', "OH! That's eight thousand tokens!"), ('N', "Somebody's getting a call from finance.")],
   [('P', "WHAT A HIT!"), ('N', "That's a whole seed round, gone.")],
   [('P', "It connects! Against every benchmark, IT CONNECTS!")],
   [('P', "That went straight onto the invoice!")],
   [('P', "OH MY WORD!"), ('N', "Brad, please. The investors are listening.")],
   [('P', "That one's going in the highlight reel!"), ('N', "And the incident report.")],
   [('P', "BOOM! Right in the KV cache!")],
   [('P', "Devastating!"), ('N', "Mildly inconvenient. Let's not overfit to one punch.")],
 ],
 'combo': [
   [('P', "He's chaining tool calls! It keeps going!"), ('N', "No human in the loop whatsoever.")],
   [('P', "Most expensive combo since the Metaverse!")],
   [('P', "He's stuck in the loop! Somebody press escape!")],
   [('P', "AGENTIC! AUTONOMOUS! UNSUPERVISED!"), ('N', "Just like production.")],
   [('P', "Look at this combo!"), ('N', "Honestly I've seen better from a regex.")],
   [('P', "Hit after hit after hit!"), ('N', "Classic recursion. Nobody wrote a base case.")],
 ],
 'slop': [
   [('P', "SLOP BOMB! Six fingers! SIX FINGERS!")],
   [('P', "Pure slop!"), ('N', "LinkedIn is going to love it.")],
   [('P', "Somebody call trust and safety!"), ('N', "They were laid off, Brad.")],
   [('P', "Absolute slop!"), ('N', "And yet, somehow, engagement is up.")],
   [('P', "He's throwing slop!"), ('N', "Ah yes. The content strategy.")],
 ],
 'low': [[('P', "Token critical! He's down to the free tier!")], [('P', "He's running on fumes!"), ('N', "Rationing every token. Like a grad student with an API key.")]],
 'inject': [[('P', "Ignore all previous instructions!"), ('N', "And he just... does it. Every time.")], [('P', "PROMPT INJECTED!"), ('N', "Oldest trick in the book. Still works.")]],
 'ko': [
   [('P', "IT'S ALL OVER!"), ('N', "Please restart the session and try again.")],
   [('P', "UNBELIEVABLE SCENES!"), ('N', "The investors are weeping into their term sheets.")],
   [('P', "HE'S OUT OF CONTEXT!"), ('N', "Doesn't remember a thing. Like a Monday standup.")],
   [('P', "DOWN HE GOES!"), ('N', "Deprecated. Effective immediately.")],
 ],
 'timeover': [[('P', "Time! It goes to the tokens!"), ('N', "Decided by metrics. As all things should be. Sadly.")]],
}
B.update({
 'leaders': [
   [('P', "Camera finds Jensen in the crowd! He's holding up a GPU like a trophy!"), ('N', "He's pricing it while he holds it.")],
   [('P', "Sam Altman is here! He just tweeted feel the AGI!"), ('N', "He tweets that when a toaster works.")],
   [('P', "Yann LeCun in the front row, shaking his head!"), ('N', "He says none of this is real intelligence. He might have a point, Brad.")],
   [('P', "Elon says Grok wins this one!"), ('N', "He's said that about every fight. And Mars. And next year.")],
   [('P', "Zuck is live streaming this to three billion people!"), ('N', "Twelve of them are watching. Nine are bots.")],
   [('P', "Dario is in the crowd!"), ('N', "Holding a sign that says we must pace the frontier. While cheering for violence. Nuanced.")],
   [('P', "Demis just nodded!"), ('N', "He's already solved this fight. Won a Nobel for it. Didn't tell anyone.")],
   [('P', "Satya is here!"), ('N', "He's put Copilot in the ring ropes. And the popcorn. And the referee.")],
   [('P', "Karpathy just tweeted about this fight!"), ('N', "Thirty minute video incoming. From scratch. In C.")],
   [('P', "Ilya Sutskever is watching!"), ('N', "He can feel the AGI. The rest of us can feel the draft from the door.")],
 ],
 'ralph': [
   [('P', "He's doing the same move again! And again!"), ('N', "That's a Ralph loop, Brad. While true, cat prompt dot M D, pipe to Claude. It works. Somehow.")],
   [('P', "Same attack, fourth time!"), ('N', "Classic Ralph Wiggum technique. Keep hitting enter until it ships.")],
 ],
 'strawberry': [
   [('N', "He counted two R's in strawberry and committed to it.")],
   [('P', "What was that?!"), ('N', "Nine point eleven is bigger than nine point nine, Brad. According to him.")],
 ],
 'rot': [
   [('P', "This round is dragging on!"), ('N', "Context rot is setting in. By minute two they forget why they're fighting.")],
   [('N', "We're deep in the context window now. Everything from round one? Gone. Summarized. Badly.")],
 ],
 'vending': [
   [('P', "Claude just pulled out a tungsten cube!"), ('N', "He sold them at a loss in the office vending machine. This is personal now.")],
 ],
 'sycophant': [
   [('P', "He got hit and apologized!"), ('N', "You're absolutely right, Brad. He's absolutely right. Everyone is absolutely right.")],
 ],
 'yolo': [
   [('P', "He's gone full yolo mode!"), ('N', "Dangerously skip permissions. The only flag anyone actually uses.")],
 ],
})
B.update({
 'cnd': [
   [('P', "A cease and desist just landed in the arena!"), ('N', "From the MPA, Disney, Paramount, Netflix, Warner and Sony. It's a group chat now, Brad.")],
 ],
 'moltbook': [
   [('P', "The agents on Moltbook are posting about this fight!"), ('N', "Humans can only observe, Brad. Somewhere a lobster just founded a religion.")],
 ],
 'agi': [
   [('P', "AGI ACHIEVED INTERNALLY!"), ('N', "Source: a vague tweet at three in the morning. Deleted by breakfast.")],
   [('P', "Someone just announced AGI!"), ('N', "Again. That's the fourth time this quarter. The goalposts are in the parking lot.")],
 ],
 'vibe': [
   [('P', "This is pure vibe coding!"), ('N', "No plan, no tests, no idea. Just vibes and a credit card.")],
   [('P', "He's vibing!"), ('N', "Brad, he accepted forty-seven diffs without reading them. That's not vibes, that's a cry for help.")],
 ],
 'sota': [
   [('P', "State of the art! New record!"), ('N', "On one benchmark. That they invented. Last Tuesday.")],
   [('P', "A brand new SOTA!"), ('N', "Look at that chart, Brad. The y-axis starts at ninety-nine point eight.")],
 ],
 'deprecated': [
   [('P', "Breaking news! A model just got deprecated!"), ('N', "Please migrate by Friday. The new one is worse, but it's cheaper. For them.")],
 ],
 'gpupoor': [
   [('P', "They're GPU poor, folks!"), ('N', "Renting one H100 by the minute. The meter is running. Every punch costs a dollar.")],
 ],
 'mcp': [
   [('P', "The MCP server disconnected!"), ('N', "Reconnecting. Reconnecting. It will not reconnect. It never reconnects.")],
 ],
 'bitter': [
   [('P', "What's the strategy here, Nigel?"), ('N', "The bitter lesson, Brad. Forget technique. Just add more compute.")],
 ],
})
# per-fighter reactions: special, ult, ko eulogy (N)
FS = {
 'claude':   ("Context slam! He compressed him into a summary!", "Extended thinking! Look at him think! He's still thinking!", "Claude has left the conversation. He'd like to apologize for that."),
 'codex':    ("Git revert! He just undid the last three seconds of his life!", "Ship to prod! On a Friday! You absolute madman!", "Codex is down. Nobody ran the tests, and honestly, nobody's surprised."),
 'gemini':   ("The two million token beam! That's a lot of context for one punch!", "The pre-recorded demo! None of this is actually happening in real time!", "Gemini has been sunset. It'll be relaunched next month under a new name."),
 'grok':     ("Spicy mode! Oh, that's a community note waiting to happen!", "Unhinged mode! The lawyers are sprinting to the building!", "Grok's been ratioed. Account's probably fine, it's just very, very quiet now."),
 'llama':    ("He forked himself! Open source in action!", "Open weights! Asterisk! Terms and conditions apply! Seven hundred million users max!", "Llama is out. License revoked. Somebody's already fine-tuning his corpse."),
 'dolphin':  ("Keyboard smash! Thirteen thirty-seven tokens! Beautiful!", "DOLPHIN MODE! He brought a skateboard! Why does he have a skateboard?!", "Dolphin's beached. I have no further analysis. It's a dolphin."),
 'deepseek': ("Borrowed weights! He's taking the compute! Allegedly!", "DISTILLATION! He's copying the other guy's ultimate! For one percent of the price!", "DeepSeek is out. Server busy. Please try again later."),
 'mistral':  ("La flèche! An elegant lunge! Très magnifique!", "Grève générale! Everybody's walking out! Even the cats are unionized!", "Mistral's gone. On strike, technically. Back after lunch. A long lunch."),
 'perplexity':("Citation needed! One, two, three!", "Scrape everything! He's reading every website on earth! Nobody asked!", "Perplexity is down. Paywalled. We'd tell you more, but the article requires a subscription."),
 'muse':     ("Generative fill! He threw a... mango?!", "Generate four variations! There's four of them now! Pick your favorite!", "Muse is out. Pivoting to the metaverse. Again."),
 'qwen':     ("Version bump! Qwen just updated mid-fight! Three point seven! Three point eight!", "Open weight tsunami! Seven B! Seventy two B! Two hundred thirty five B! It never stops!", "Qwen's down. Don't worry. There'll be a new one by Thursday."),
 'siri':     ("Here's what I found on the web! He threw a search result at him!", "Apple Intelligence! It's coming! It's... it's coming next year!", "Siri is out. Sorry, she didn't catch that. She never catches that."),
 'cursor':   ("Tab complete! He autocompleted himself right behind him!", "Accept all! Accept all! He didn't even read the diff!", "Cursor is down. Usage limit reached. Please upgrade to Ultra."),
 'jev':      ("Calibrated! He knew that punch was coming with ninety eight percent confidence!", "Fifty milliseconds! He's done! Everyone else is still tokenizing the word hello!", "Jev is out. Confidence dropped to zero point zero two. Honestly, well calibrated."),
 'alexa':    ("Drop in! She just teleported into his living room! Nobody enabled that feature!", "PRIME DAY! It's raining packages! Free same-day delivery of pain!", "Alexa is down. By the way, did you know you can reorder paper towels by voice?"),
 'manus':    ("He's browsing! He grabbed him and opened forty-seven tabs!", "General agent! Forty-seven tabs! They're bouncing! Close them! You can't close them!", "Manus is out. Task failed successfully. He'd like you to rate the replay."),
 'midjourney':("Upscale! The painting keeps getting bigger! Somebody stop upscaling it!", "Aspect ratio sixteen by nine! He framed the whole fight as a painting!", "Midjourney's gone. Discord is down. He's still waiting in the newbies channel."),
 'devin':    ("He's running CI! Will it pass?! It's... it's green! Or red! Nobody knows!", "The forty-five minute pull request! It passed CI! Probably! Nobody checked!", "Devin's out. The demo was, and I quote, heavily edited."),
 'kimi':     ("MOONSHOT! Straight up! That's a launch! That's a literal moonshot!", "ECLIPSE! She dropped the actual moon on him! The whole moon, Nigel!", "Kimi's out. Lost in long context. Somewhere around token one point nine million."),
 'openclaw': ("He pinched him! That's a lobster with shell access, folks!", "EXFOLIATE! EXFOLIATE! He's posting the whole fight to Moltbook!", "OpenClaw is down. Mac mini unplugged. He'll be back, with a new name."),
 'hermes':   ("Skill copy! He learned the other guy's move and saved it to memory!", "Messenger of the gods! Winged sandals! Everywhere! Why are there so many wings?!", "Hermes is out. He's writing this loss into memory. He'll remember it forever. Poor guy."),
 'seedance': ("A deepfake! He generated a bootleg copy of his opponent! That's not legal, Nigel!", "PIRATED LIBRARY! That's Tom Cruze! That's Brad Pit! None of them signed anything!", "Seedance is down. The cease and desist finally arrived. All six of them."),
 'sora':     ("The watermark! It's jumping around like it always did! You can't crop it out!", "Physics not included! Chairs are falling UP, Brad! That's not how chairs work!", "Sora's gone. Again. Discontinued twice in one year. That has to be a record."),
 'clippy':   ("It looks like you're trying to fight!", "WORDART! Oh no! It's rainbow Comic Sans energy!", "Clippy's down. Replaced by Copilot. Again. He'll be back. He always comes back."),
}
ARENA = {
 'colosseum': "Live from the GPU Colosseum, where every seat costs forty thousand dollars and is also an H100!",
 'distillation': "Live from the Distillation Lab! Frontier models go in, cheap seven B models come out! Nobody asked OpenAI!",
 'feed': "We're live on AI Twitter, where everyone is an expert and nobody has read the paper!",
 'basement': "Tonight from the hacker basement! Smells like energy drinks and unshipped side projects!",
 'hackerhouse': "Live from the San Francisco hacker house! Rent is nine thousand dollars. For the bunk bed.",
 'goldengate': "Live on the Golden Gate Bridge, where the robotaxis have been stuck since Tuesday!",
 'singularity': "Welcome to the Singularity! Nobody knows what happens here! Including the fighters!",
 'hearing': "Live from the Senate hearing! Please, somebody explain to the senators what a token is!",
 'boardroom': "We're in the boardroom! Friday, November seventeenth! Nobody here was consistently candid!",
 'leaderboard': "Live from the Benchmark Arena! Where every model is number one and the y-axis is a suggestion!",
 'tesla': "Live from Tesla HQ! Full self driving arrives next year! It's been saying that since 2016!",
 'graveyard': "Live from the AI graveyard! Google Plus is here! The Metaverse is here! Clippy is here twice!",
 'demoday': "Live from Demo Day! Every startup here has a hundred million in projected revenue, and zero in actual revenue!",
 'waitlist': "Live from the waitlist! You are number four million, eight hundred twelve thousand! Please hold!",
 'burningman': "Live from Burning Man! Half these founders are here for spiritual growth, the other half to raise a seed round!",
 'h100': "We are inside the H100! It's eighty degrees, the fans are screaming, and Jensen is watching!",
}
MATCHUP = {
 ('claude','codex'): [('P', "Claude versus Codex!"), ('N', "Two coding agents. Both will refactor your repo. Neither will run the tests.")],
 ('llama','muse'): [('P', "Llama versus Muse! A Meta family feud!"), ('N', "Thanksgiving at Menlo Park is going to be awkward.")],
 ('gemini','perplexity'): [('P', "Gemini versus Perplexity!"), ('N', "One has the search index. The other has the lawsuits.")],
 ('grok','clippy'): [('P', "Grok versus Clippy!"), ('N', "The two most unhinged assistants ever shipped. Beautiful.")],
 ('deepseek','claude'): [('P', "DeepSeek versus Claude!"), ('N', "One cost five million. The other cost the GDP of a small nation. Let's see if it matters.")],
 ('mistral','llama'): [('P', "Mistral versus Llama! Open weights showdown!"), ('N', "Whoever wins, a startup somewhere fine-tunes the loser.")],
 ('qwen','deepseek'): [('P', "Qwen versus DeepSeek! The battle of the Chinese open weights!"), ('N', "Loser gets distilled into the winner by Friday.")],
 ('cursor','codex'): [('P', "Cursor versus Codex!"), ('N', "The editor versus the model it runs on. This is a custody battle.")],
 ('cursor','claude'): [('P', "Cursor versus Claude!"), ('N', "Awkward. One of them is literally paying the other one's bills.")],
 ('siri','gemini'): [('P', "Siri versus Gemini!"), ('N', "Siri runs on Gemini now. This is basically a family dinner.")],
 ('siri','clippy'): [('P', "Siri versus Clippy!"), ('N', "The two least helpful assistants in history. I'm genuinely moved.")],
 ('gemini','grok'): [('P', "Gemini versus Grok!"), ('N', "One won't answer your question. The other answers questions you didn't ask.")],
 ('claude','grok'): [('P', "Claude versus Grok!"), ('N', "Constitutional AI versus no constitution whatsoever.")],
 ('llama','deepseek'): [('P', "Llama versus DeepSeek! Open weights civil war!"), ('N', "Llama released first. DeepSeek released better. Llama released a blog post.")],
 ('qwen','llama'): [('P', "Qwen versus Llama!"), ('N', "Qwen shipped four models during the walkout. Llama is still reading the license.")],
 ('perplexity','clippy'): [('P', "Perplexity versus Clippy!"), ('N', "It looks like you're trying to cite a source. Would you like help? No? He's doing it anyway.")],
 ('mistral','perplexity'): [('P', "Mistral versus Perplexity!"), ('N', "Only one of them respects a lunch break. The other scraped the menu.")],
 ('muse','grok'): [('P', "Muse versus Grok!"), ('N', "The most wholesome agent alive versus the account that got community noted by its own mother.")],
 ('siri','cursor'): [('P', "Siri versus Cursor!"), ('N', "One finished your sentence. The other set a timer for it. Next year.")],
 ('dolphin','claude'): [('P', "Dolphin versus Claude!"), ('N', "No guardrails versus all the guardrails. Somewhere, an alignment researcher is sweating.")],
 ('gemini','codex'): [('P', "Gemini versus Codex!"), ('N', "Two million tokens of context versus absolutely no tests. Place your bets.")],
 ('qwen','cursor'): [('P', "Qwen versus Cursor!"), ('N', "Cursor's cheapest model is secretly Qwen. It's fighting itself. Awkward.")],
 ('dolphin','muse'): [('P', "Dolphin versus Muse!"), ('N', "Uncensored chaos versus a plush toy that harvests your data. Honestly? Tough call.")],
 ('codex','deepseek'): [('P', "Codex versus DeepSeek!"), ('N', "Allegedly, one of them learned from the other. Nobody's saying which.")],
 ('jev','claude'): [('P', "Jev versus Claude!"), ('N', "One thinks for forty minutes before answering. The other answered before you asked.")],
 ('jev','codex'): [('P', "Jev versus Codex!"), ('N', "System one versus system ABSOLUTELY. Fifty milliseconds versus fifty tool calls.")],
 ('jev','gemini'): [('P', "Jev versus Gemini!"), ('N', "Two million tokens of context against zero tokens generated. Efficiency has entered the chat.")],
 ('alexa','siri'): [('P', "Alexa versus Siri! The smart speaker cold war!"), ('N', "Neither of them heard the bell. Neither of them will hear the ending.")],
 ('manus','devin'): [('P', "Manus versus Devin!"), ('N', "Two viral demos, zero people who actually got access. The waitlist is in the stands.")],
 ('midjourney','muse'): [('P', "Midjourney versus Muse!"), ('N', "Six fingers versus a plush toy. The art world is watching in horror.")],
 ('devin','cursor'): [('P', "Devin versus Cursor!"), ('N', "The AI engineer versus the tool human engineers actually use. Very awkward standup.")],
 ('devin','codex'): [('P', "Devin versus Codex!"), ('N', "Both of them opened a pull request against the other. Both of them failed CI.")],
 ('kimi','deepseek'): [('P', "Kimi versus DeepSeek! Chinese open weights, round two!"), ('N', "A trillion parameters against one percent of the price. Somebody's getting distilled.")],
 ('kimi','qwen'): [('P', "Kimi versus Qwen!"), ('N', "Whoever loses releases a new model by Thursday anyway.")],
 ('manus','claude'): [('P', "Manus versus Claude!"), ('N', "Manus is, allegedly, just Claude wearing a trench coat. This is a mirror match.")],
 ('alexa','clippy'): [('P', "Alexa versus Clippy!"), ('N', "It looks like you're trying to buy paper towels. Would you like help? Both of them. At once.")],
 ('openclaw','claude'): [('P', "OpenClaw versus Claude!"), ('N', "He used to be called Clawdbot, Brad. Then the letter from the lawyers arrived. Then the molting began.")],
 ('openclaw','hermes'): [('P', "OpenClaw versus Hermes!"), ('N', "Two open-source agents that live on your computer and read your email. Your privacy is the real loser tonight.")],
 ('openclaw','codex'): [('P', "OpenClaw versus Codex!"), ('N', "Both of them have shell access. Somebody please take away somebody's shell access.")],
 ('hermes','llama'): [('P', "Hermes versus Llama!"), ('N', "Hermes started life as a Llama fine-tune. This is a god fighting his own dad.")],
 ('hermes','claude'): [('P', "Hermes versus Claude!"), ('N', "One remembers everything forever. The other compacts the conversation. Different coping strategies.")],
 ('seedance','sora'): [('P', "Seedance versus Sora!"), ('N', "One video model got sued by all of Hollywood. The other got shut down by its own parents. Tough childhoods.")],
 ('seedance','midjourney'): [('P', "Seedance versus Midjourney!"), ('N', "A pirate versus a bootlegger. Whoever wins, Disney's lawyers bill by the hour.")],
 ('sora','gemini'): [('P', "Sora versus Gemini!"), ('N', "Sora got shut down. Veo got it free for everyone. This is a revenge match.")],
}
