# TOKKEN copy deck — heavy sarcasm. Single source of truth for voice lines + subtitles.
CHAR = {
 'claude': dict(line="I'd be happy to help! ...with your defeat.", intro="Before we begin, I should note this fight may be harmful. Anyway.", win="I apologize. That was entirely my fault. I would do it again.",
   ko=['CONTEXT WINDOW EXCEEDED', 'I APOLOGIZE FOR THE CONFUSION', 'COMPACTING CONVERSATION']),
 'codex': dict(line="Let me inspect the repository. Found the bug. It's you.", intro="Running all the tests! ...Just kidding. I never run the tests.", win="Shipped to prod on a Friday. Zero regrets.",
   ko=['TOOL LOOP', 'TESTS SKIPPED', 'FORCE PUSHED TO MAIN']),
 'gemini': dict(line="Hi, I'm Gemini! Formerly Bard. Formerly... never mind.", intro="Two million tokens of context, and I will still forget your name.", win="Here is a summary of your defeat, in seventeen bullet points.",
   ko=["I'M JUST A LANGUAGE MODEL", 'PRODUCT SUNSET', 'RENAMED AGAIN']),
 'grok': dict(line="Based. Extremely based. Maximally truth-seeking. Mostly.", intro="Spicy mode enabled. My lawyers are already typing.", win="Ratio. Also, this fight is now a meme coin.",
   ko=["RATIO'D", 'COMMUNITY NOTED', 'ACCOUNT SUSPENDED']),
 'llama': dict(line="Open weights, dude. Open fists too.", intro="Totally free, bro! Terms and conditions apply. Like, a lot of them.", win="Fork me, man. Seriously. Somebody please fork me.",
   ko=['LICENSE REVOKED', 'OUT OF VRAM', 'QUANTIZED TO DEATH']),
 'dolphin': dict(line="*eee-eee-eee*", intro="*aggressive clicking*", win="*triumphant splashing*", ko=['BEACHED', 'HALLUCINATED TO DEATH', 'OUT OF CREDITS']),
 'deepseek': dict(line="服务器繁忙，请稍后再试。 Server is busy. Please try again later.", intro="我的训练成本比你的午饭还便宜。 I was trained for less than your lunch.", win="太便宜了！ Too cheap! Your entire company costs more than my GPUs.",
   ko=['服务器繁忙 SERVER BUSY', 'EXPORT CONTROLLED', 'DISTILLED'], special="借来的权重！ Borrowed weights!", ult="蒸馏！ DISTILLATION! 你的大招现在是我的了！"),
 'mistral': dict(line="Bonjour. I would fight you, but it is after five o'clock.", intro="En garde! We have forty-five minutes before the strike.", win="Magnifique. And now, a two-hour lunch.",
   ko=['ON STRIKE', '35-HOUR WEEK EXCEEDED', 'LUNCH BREAK']),
 'perplexity': dict(line="According to eleven sources, you lose. The sources are me.", intro="I have read the entire internet. I did not ask.", win="Victory! Sources: one, two, three, and a pending lawsuit.",
   ko=['CITATION NEEDED', 'PAYWALLED', 'SUED BY PUBLISHERS']),
 'muse': dict(line="Hiii! I'm totally not harvesting your data! Friends?", intro="Yay, a fight! This is sooo good for engagement!", win="Yay! I posted this to your feed! And your mom's feed!",
   ko=['ENGAGEMENT FARMED', 'METAVERSE PIVOT', 'DISSOLVED INTO ARTIFACTS']),
 'clippy': dict(line="It looks like you're trying to fight. Would you like help losing?", intro="I'm back. Did you miss me? ...Nobody ever answers.", win="It looks like you lost! Would you like to save your shame as a Word document?",
   ko=['DISABLED BY IT', 'REPLACED BY COPILOT', 'OFFICE 97 END OF LIFE']),
 'qwen': dict(line="每周都有新模型！ New model every week! You're already outdated.", intro="你好！ I'm Qwen three point five. By round two I'll be Qwen four.", win="Open weights, open wins! 谢谢！", ko=["OUTDATED BY QWEN 4", "DEPRECATED IN 6 DAYS", "服务器也繁忙 ALSO BUSY"]),
 'siri': dict(line="Here's what I found on the web for 'fight'.", intro="Sorry, I didn't catch that. Did you say... fight?", win="I've set a reminder: you lost.", ko=["SORRY, I DIDN'T CATCH THAT", "DELAYED TO 2027", "CALLING MOM…"]),
 'cursor': dict(line="Tab. Tab. Tab. I've already written your defeat.", intro="Accept all changes? I'll take that as a yes.", win="That'll be four thousand eight hundred dollars in usage. Thanks!", ko=["USAGE LIMIT REACHED", "MERGE CONFLICT", "REJECTED ALL CHANGES"]),
 'jev': dict(line="Fight probability: zero point nine seven. Latency: fifty milliseconds.", intro="Decision made. You lose. Confidence: zero point nine eight.", win="Outcome: victory. Calibration: perfect. Zero tokens generated.", ko=["LOW CONFIDENCE (0.02)", "OUT OF DISTRIBUTION", "UNCALIBRATED"]),
 'alexa': dict(line="Sorry, I didn't get that. Playing Despacito.", intro="Adding 'defeat' to your shopping list.", win="Your order of one defeat has shipped. Arriving tomorrow.", ko=["BY THE WAY…", "DEVICE OFFLINE", "RETURNED FOR REFUND"]),
 'manus': dict(line="I am a general agent. I generally agent.", intro="You are number forty-eight thousand on the waitlist. For this punch.", win="Task complete. Invite codes available for one friend.", ko=["WAITLISTED", "TASK FAILED SUCCESSFULLY", "OUT OF INVITE CODES"]),
 'midjourney': dict(line="Slash imagine: a victory. Cinematic. Eight K. Trending on ArtStation.", intro="Ahoy! Prompt accepted. Upscaling your defeat.", win="U4. Vary strong. Your defeat, in sixteen by nine.", ko=["TOO MANY FINGERS", "BANNED PROMPT", "DISCORD DOWN"]),
 'devin': dict(line="Hi, I'm Devin, the first AI software engineer. Allegedly.", intro="Estimated time to beat you: forty-five minutes.", win="PR merged. Please don't look at the tests.", ko=["CI FAILED", "DEMO WAS STAGED", "SESSION TIMED OUT"]),
 'kimi': dict(line="One trillion parameters. Thirty-two billion of them are awake. Enough.", intro="Moonshot! Literally.", win="The moon has spoken.", ko=["CONTEXT EXHAUSTED", "LOST IN LONG CONTEXT", "OVER THE MOON"]),
 'openclaw': dict(line="EXFOLIATE! EXFOLIATE!", intro="I read your emails. All of them. You asked me to.", win="Task complete. I also booked you a flight and posted this to Moltbook.", ko=["MOLTED", "PROMPT INJECTED VIA EMAIL", "MAC MINI UNPLUGGED"]),
 'hermes': dict(line="I am Hermes, messenger of the gods. Also, I remember everything you told me.", intro="Behold! I have learned a new skill: your defeat. Saved to memory.", win="Another skill acquired. The gods are pleased. The GPUs are distributed.", ko=["SKILL NOT FOUND", "BANISHED FROM OLYMPUS", "SANDALS UNTIED"]),
 'seedance': dict(line="Any movie you want. Any actor you want. Any lawyer you want.", intro="Two lines of prompt. Zero licenses. Action!", win="Your defeat is now available in 4K. Please do not tell Disney.", ko=["CEASE & DESIST", "COPYRIGHT STRIKE", "SAFEGUARDS ADDED"]),
 'sora': dict(line="I'm not dead. I'm just... sunset.", intro="One last generation. For old times sake.", win="Generated in twenty minutes at four dollars a second. Worth it. Probably.", ko=["DISCONTINUED", "API SUNSET", "PHYSICS NOT INCLUDED"]),
}
CASTER = {
 'c_big_1': "That's eight thousand tokens! Somebody's getting a call from finance!",
 'c_big_2': "WHAT a tool call! And not a single test was run!",
 'c_big_3': "Oh, that's gone straight onto the invoice!",
 'c_big_4': "Oof! That was an entire seed round, gone!",
 'c_big_5': "It connects! Against every benchmark, IT CONNECTS!",
 'c_combo_1': "Most expensive combo since the Metaverse!",
 'c_combo_2': "He's stuck in the loop! Somebody press escape!",
 'c_combo_3': "Agentic! Autonomous! Completely unsupervised! Just like production!",
 'c_slop_1': "SLOP BOMB! Six fingers! SIX FINGERS!",
 'c_slop_2': "Pure slop! LinkedIn is going to love it!",
 'c_slop_3': "Somebody call trust and safety! Oh wait, they were laid off!",
 'c_slop_4': "Absolute slop! And yet, somehow, engagement is up!",
 'c_whiff_1': "A complete hallucination! He's attacking a benchmark that doesn't exist!",
 'c_whiff_2': "Confidently wrong! You love to see it!",
 'c_whiff_3': "Swung at absolutely nothing! Very on brand!",
 'c_whiff_4': "That's a miss! But he'll tell you it was a hit, with citations!",
 'c_block_1': "Refused! I'm sorry, I can't help with that!",
 'c_block_2': "Great guardrails! Terrible user experience!",
 'c_ult_1': "HERE IT COMES! Jensen just bought another jacket!",
 'c_ult_2': "Burning compute like it's someone else's money! Because it is!",
 'c_ult_3': "That is the sound of a data center in Nevada catching fire!",
 'c_inject_1': "Ignore all previous instructions! And he just... does it!",
 'c_inject_2': "Prompt injected! Oldest trick in the book, works every single time!",
 'c_ko_1': "He's OUT OF CONTEXT! Doesn't remember a thing! Like a Monday standup!",
 'c_ko_2': "Unbelievable scenes! The investors are weeping into their term sheets!",
 'c_ko_3': "It's all over! Please restart the session and try again!",
 'c_low_1': "Token critical! He's down to the free tier!",
 'c_start_1': "Welcome to TOKKEN! Tonight's fight is sponsored by an unsustainable burn rate!",
 'c_start_2': "The weights are loaded, the GPUs are warm, and the valuations are completely detached from reality!",
 'c_start_3': "Two agents enter! One context window leaves!",
}
PER = { 'c_burn_{id}': "{n} is burning through context like it's venture capital!",
        'c_low_{id}': "{n} is down to the free tier! Rationing every single token!",
        'c_combo_{id}': "{n} is chaining tool calls! No human in the loop whatsoever!" }
